version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: franciscoavila
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  backend:
    build: ./server
    container_name: django_container
    command: sh -c "gunicorn server_proj.wsgi --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
  nginx:
    build: ./client
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - backend

